mode: rule

proxy-groups:
  - name: 🚀 节点选择
    type: select
    include-all: true
    include-all-proxies: true
    include-all-providers: true

rules:
  # UDP 443 禁止 QUIC
  - AND,((NETWORK,UDP),(DST-PORT,443)),REJECT

  # 局域网
  - GEOIP,PRIVATE,DIRECT

  # 国内直连
  - GEOIP,CN,DIRECT
  - GEOSITE,CN,DIRECT
  - DOMAIN-SUFFIX,local,DIRECT

  # Steam 下载直连
  - DOMAIN-SUFFIX,steamcontent.com,DIRECT

  # Apple 直连
  - RULE-SET,Apple,DIRECT

  # 广告拦截
  - RULE-SET,BanAD,REJECT

  # 其他全部代理
  - MATCH,🚀 节点选择

rule-providers:
  Apple:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Apple.list
    path: ./providers/Apple.list
    interval: 86400

  BanAD:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BanAD.list
    path: ./providers/BanAD.list
    interval: 86400
