[custom]

; 局域网
ruleset=DIRECT,[]GEOIP,PRIVATE

; 国内直连
ruleset=DIRECT,[]GEOIP,CN
ruleset=DIRECT,[]GEOSITE,CN
ruleset=DIRECT,[]DOMAIN-SUFFIX,local

; Steam 下载直连
ruleset=DIRECT,[]DOMAIN-SUFFIX,steamcontent.com

; Apple直连
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Apple.list

; 广告拦截
ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list

; 其他全部代理
ruleset=🚀 节点选择,[]FINAL

custom_proxy_group=🚀 节点选择`select`.*

enable_rule_generator=true
overwrite_original_rules=true
