mode: rule

proxy-groups:

  - name: 🚀 节点选择
    type: select
    include-all: true

rules:

  # UDP 443 禁止 QUIC
  - AND,((NETWORK,UDP),(DST-PORT,443)),REJECT

  # 局域网 IP 直连
  - GEOIP,PRIVATE,DIRECT

  # 局域网域名直连
  - GEOSITE,PRIVATE,DIRECT

  # 国内 IP 直连
  - GEOIP,CN,DIRECT

  # 国内域名直连
  - GEOSITE,CN,DIRECT

  # Steam 下载直连
  - DOMAIN-SUFFIX,steamcontent.com,DIRECT

  # Apple 服务直连
  - GEOSITE,apple,DIRECT

  # 微软服务直连
  - GEOSITE,microsoft,DIRECT

  # 其他全部代理
  - MATCH,🚀 节点选择
